spring:
  profiles:
    include: [ common-dev ]
  rabbitmq:
    virtual-host: novel
    addresses: "amqp://novel:test123456@192.168.1.5"
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: "3s"
    publisher-confirms: true

pic:
  save:
    type: 2 #图片保存方式, 1不保存，使用爬取的网络图片 ，2保存在自己的存储介质
    storage: OSS #存储介质，local：本地，OSS：阿里云对象存储
    path: picture  #图片保存路径



#线程池配置
thread:
  pool:
    #核心线程池数量
    core-pool-size: 200
#    core-pool-size: 200
    #最大线程池数量
    maximum-pool-size: 1000
#    maximum-pool-size: 1000
    #线程超时时间（秒）
    keep-alive-time: 10
    #队列大小
    queue-size: 1000

elasticsearch:
  hosts: 192.168.200.142
  port: 9200
  enable: true

nginx:
  address: 192.168.1.5
  port: 22
#  directoryPath: /www/server/nginx/html/index/
  directoryPath: /home/scycz4/Desktop/
  server:
    username: scycz4
    password: 84225128Xz!,.


aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: javaweb-web-tlias
    region: cn-beijing
    accessKeyId: LTAI5tSH4PwyqskiACqiTjU2
    accessKeySecret: YXpX3DgyqiqClc0d9XwaleE5x5VCEY

