spring:
  profiles:
    include: [ common-dev ]
  rabbitmq:
    virtual-host: novel
    addresses: "amqp://novel:test123456@192.168.1.5"
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: "3s"


pic:
  save:
    type: 2 #图片保存方式, 1不保存，使用爬取的网络图片 ，2保存在自己的存储介质
    storage: local #存储介质，local：本地，OSS：阿里云对象存储
    path: C:\Users\10253\Desktop\novel-plus  #图片保存路径



#线程池配置
thread:
  pool:
    #核心线程池数量
    core-pool-size: 10
    #最大线程池数量
    maximum-pool-size: 20
    #线程超时时间（秒）
    keep-alive-time: 10
    #队列大小
    queue-size: 100

elasticsearch:
  hosts: 192.168.200.142
  port: 9200


